export const homeObjOne = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Josean López Sekulits",
  headLine: "Permíteme ayudarte a encontrar la propiedad de tus sueños!",
  description: "Empresa élite dedicada a la venta y alquiler de propiedades residenciales y comerciales.¡DM para vender y/o buscar tu propiedad; y para más información llamar al 787-607-6686 o escribirnos un email al bienesraices@empireelevenrealty.com!",
  imgStart: false,
  img: require("../../images/ceo.jpg").default,
  alt: "intro",
  dark: true,
  primary: false,
  darkText: true,
};